// Types for PDF annotations generated by the AI tutor

export type AnnotationType = 'highlight' | 'circle' | 'underline' | 'box';

export interface PDFAnnotation {
  id: string;
  type: AnnotationType;
  pageNumber: number;
  // Bounding box coordinates as percentages (0-100) of the page dimensions
  // This allows annotations to scale with zoom
  bounds: {
    x: number;      // Left position (%)
    y: number;      // Top position (%)
    width: number;  // Width (%)
    height: number; // Height (%)
  };
  // The text content that should be highlighted (for search/match)
  textContent?: string;
  // Color for the annotation
  color?: string;
  // Optional label to display
  label?: string;
}

export interface AnnotationReference {
  pageNumber: number;
  annotations: PDFAnnotation[];
  sourceText: string;       // The relevant text from the document
  explanation?: string;     // Brief explanation of why this is relevant
}

export interface ChatMessageWithAnnotations {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  annotations?: AnnotationReference[];
}

// Command from chat to PDF viewer
export interface PDFNavigationCommand {
  type: 'navigate' | 'annotate' | 'clear';
  pageNumber?: number;
  annotations?: PDFAnnotation[];
}

