// Types for PDF annotations generated by the AI tutor

export type AnnotationType = 'highlight' | 'circle' | 'underline' | 'box';

export interface PDFAnnotation {
  id: string;
  type: AnnotationType;
  pageNumber: number;
  // Bounding box coordinates as percentages (0-100) of the page dimensions
  // This allows annotations to scale with zoom
  bounds: {
    x: number;      // Left position (%)
    y: number;      // Top position (%)
    width: number;  // Width (%)
    height: number; // Height (%)
  };
  // The text content that should be highlighted (for search/match)
  textContent?: string;
  // Color for the annotation
  color?: string;
  // Optional label to display
  label?: string;
}

export interface AnnotationReference {
  pageNumber: number;
  annotations: PDFAnnotation[];
  sourceText: string;       // The relevant text from the document
  explanation?: string;     // Brief explanation of why this is relevant
}

export interface TokenUsage {
  model: string;
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
}

export interface AgentMetadata {
  query_classification?: {
    query_type: string;
    complexity: 'simple' | 'moderate' | 'complex';
    requires_cot: boolean;
  };
  retrieval_strategy?: string;
  quality_scores?: {
    accuracy: number;
    completeness: number;
    clarity: number;
    citation_quality: number;
    overall: number;
  };
  citation_warnings?: string[];
  verified?: boolean;
  retry_count?: number;
  performance_metrics?: {
    total_time: number;
    node_timings: Record<string, number>;
    token_usage: Record<string, TokenUsage>;
    costs: Record<string, number>;
    cache_hits: Record<string, boolean>;
    retrieval_stats?: {
      sub_questions?: number;
      chunks_retrieved?: number;
      chunks_used?: number;
    };
  };
}

export interface ChatMessageWithAnnotations {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  annotations?: AnnotationReference[];
  metadata?: AgentMetadata;
}

// Command from chat to PDF viewer
export interface PDFNavigationCommand {
  type: 'navigate' | 'annotate' | 'clear';
  pageNumber?: number;
  annotations?: PDFAnnotation[];
}

